Fix/openshift cli and summon tls error
conjurdemos/kubernetes-conjur-demo pull request #144
Opened 2021-08-19 16:13 UTC by codihuston

Hello, this PR resolves the following:

Issues with Openshift (Next)

- `ImagePullBackOff` error when pulling secretless-broker. This was resolved by explicitly specifying the full docker domain name. See `7_app_deploy.sh`
- Specify OCP CLI version 4.8.2 for the Openshift (Next) environment. This resolves some exceptions thrown when describing pods, and using the deprecated `secrets` api to generate and use image pull secrets
- The new secrets API is conditionally used based on the OCP CLI version, in efforts to preserve any older functionality from older versions of the CLI
- The MySQL image for OCP dropped support for an earlier version of TLS. Simply updating the MySQL image resolved this issue with no code changes. Thanks Kumbi!

References regarding MySQL TLS support:
- https://access.redhat.com/documentation/en-us/red_hat_support_for_spring_boot/2.1/html/release_notes_for_spring_boot_2.1/known-issues-spring-boot
- https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html

All tests are green now =) (previously OpenShift (Next) and the MySQL tests were failing across all of OpenShift).

2021-08-19 16:22 UTC, codihuston commented
I have disabled the OCP_ NEXT param in the jenkins file. That will be handled by this repo: https://github.com/conjurinc/openshift-next-suite-test

See the results of my full run of the test suite: https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/detail/fix%2Fopenshift-cli-and-summon-tls-error/1/pipeline/

2021-08-19 18:29 UTC, doodlesbykumbi requested changes
PR looking good. Left some comments and suggestions. 

I understand that the earlier commits were experimental. As the PR is nearing approval I think it's worth revisiting the commit history and potentially reducing the commits into logical wholes. Happy to chat `git rebase -i ...`

2021-08-19 18:29 UTC, doodlesbykumbi commented on ci/Dockerfile
> +    if [ ! -f ocbin/oc ]; then mv ocbin/*/oc /usr/local/bin/oc ; else mv ocbin/oc /usr/local/bin/oc; fi && \
A suggestion to avoid the branching

```suggestion
    cp "$(find ./ocbin -name 'oc' -type f | tail -1)"  /usr/local/bin/oc  && \
```

2021-08-19 18:29 UTC, doodlesbykumbi commented on 7_app_deploy.sh
> +    fi
The newer secrets API has been in the v3 CLI for some time, at least as early as the default CLI (oc v3.7.2). My suggestion is to not bother with the branching, and to just use the newer API.

```suggestion
    $cli create secret docker-registry dockerpullsecret \
        --docker-server=${PULL_DOCKER_REGISTRY_URL} \
        --docker-username=_ \
        --docker-password=$($cli whoami -t) \
        --docker-email=_
    $cli secrets link default dockerpullsecret --for=pull
```

2021-08-19 18:29 UTC, doodlesbykumbi commented on openshift/mysql.template.yml
> +        image: centos/mysql-80-centos7
I think it's worth adding comments about the choice of image for each backend.

1. `centos/mysql-80-centos7` for direct connections because the latest version of the test app would otherwise require special changes to the DB_URL secrets only for MySQL in order to avoid the TLS version mismatch issues of `centos/mysql-57-centos7`.
2. `centos/mysql-57-centos7` for connections through Secretless because it doesn't have the TLS version mismatch issue, but has an issue with `centos/mysql-80-centos7` due to lack of support for new authentication mechanism from MySQL 8.0.

2021-08-19 22:24 UTC, codihuston commented
@rpothier Sorry for the review request, Kumbi was on it--I didn't see if my original request had gone through.

Hey @doodlesbykumbi, I went ahead and cleaned up the commits a bit. Please let me know if that is adequate. Tests are running now. Thanks!

2021-08-20 15:51 UTC, codihuston commented
I went ahead and re-confirmed that tests against `openshift (next)` were still green. Disabling those tests now via `TEST_OCP_NEXT` since it seems that no projects are actively testing against this cluster by default.

See: https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/detail/fix%2Fopenshift-cli-and-summon-tls-error/9/pipeline

The test currently running now will not test against this cluster.

2021-08-20 15:54 UTC, doodlesbykumbi requested changes
@codihuston Thanks for addressing those earlier comments. Left 2 comments. The PR is currently at 5 commits, I think we could potentially reduce it all to a single (if not 2) logical commit/s.

2021-08-20 15:54 UTC, doodlesbykumbi commented on openshift/mysql.template.yml
> +        image: centos/mysql-80-centos7
@codihuston, could you please add some comments to the effect of the above so that we don't inadvertently change these images.

2021-08-20 15:54 UTC, doodlesbykumbi commented on utils.sh
> +function is_oc_major_version(){
I think we don't need these "versions" functions anymore since we took out the branching.

2021-08-20 16:08 UTC, codihuston commented on utils.sh
> +function is_oc_major_version(){
Change committed and squashed into db0ad4c

2021-08-20 16:09 UTC, codihuston commented
Added a comment on the mysql template, see d03483d. Ready for re-review =).

2021-08-20 16:55 UTC, doodlesbykumbi requested changes
A few more comments

2021-08-20 16:55 UTC, doodlesbykumbi commented on 7_app_deploy.sh
> +    echo "oc cli version: $(get_oc_version)"
Please remove, this is also not needed anymore. The build is likely failing because it can't find `get_oc_version`

2021-08-20 16:55 UTC, doodlesbykumbi commented on openshift/mysql.template.yml
> +        image: centos/mysql-80-centos7
@codihuston Please add a comment for each backend. There are 3 backends in total

2021-08-20 16:55 UTC, doodlesbykumbi commented on utils.sh
> +}
No newline at EOF

2021-08-20 19:17 UTC, codihuston commented
Comments revisited and resolved. One of the test stages is failing due to a rate-limit from docker for this image: `centos/mysql-80-centos7`. I can restart this later this afternoon to see if this kicks off. Until then please review once more. =)

2021-08-24 21:18 UTC, codihuston commented
@doodlesbykumbi Hi Kumbi. As we discussed, I've added some logic to build out a custom mysql image based on `centos/mysql-80-centos7`. In the pipeline, it is built and stored in the openshift image registry only when running against openshift clusters.

I have also reduced everything into one commit.

[Looks like all of the tests have green lights](https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/detail/fix%2Fopenshift-cli-and-summon-tls-error/20/pipeline/). While these tests include the openshift (next) cluster, jenkins should not include that cluster in future instances. See [Jenkinsfile](https://github.com/conjurdemos/kubernetes-conjur-demo/blob/fix/openshift-cli-and-summon-tls-error/Jenkinsfile).

2021-08-30 22:05 UTC, codihuston commented
Mysql v5.7 is tagged and pushed to our openshift registry in attempt to circumvent docker hub rate-limits as well. See [this pipeline](https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/detail/fix%2Fopenshift-cli-and-summon-tls-error/24/pipeline/). Note that I just re-ran the pipeline while enabling the `TEST_OCP_NEXT` flag.

Please verify my approach to injecting images into the k8s/openshift templates here: [injection of the templated values](https://github.com/conjurdemos/kubernetes-conjur-demo/blob/fix/openshift-cli-and-summon-tls-error/7_app_deploy.sh#L126-L140), particularly for k8s.

Thanks!

2021-09-01 11:25 UTC, doodlesbykumbi approved these changes

2021-09-01 11:26 UTC, merged

2021-09-01 11:27 UTC, doodlesbykumbi commented
Thanks @codihuston. Approved and merged.